definitions:
  domain.Auth:
    properties:
      dni:
        type: string
      password:
        type: string
    type: object
  domain.RecoverPassword:
    properties:
      dni:
        type: string
    type: object
  domain.ResetPassword:
    properties:
      access_token:
        type: string
      password:
        type: string
    type: object
  domain.UpdateUser:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
    type: object
  domain.User:
    properties:
      dni:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      password:
        type: string
      role:
        $ref: '#/definitions/domain.UserRole'
      type_dni:
        $ref: '#/definitions/domain.UserTypeDNI'
    type: object
  domain.UserRole:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - AdminRole
    - MedicRole
    - PatientRole
  domain.UserTypeDNI:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-comments:
      TypeDniTP: passport
    x-enum-varnames:
    - TypeDniCC
    - TypeDniTI
    - TypeDniTP
info:
  contact: {}
  title: Software2Backend
  version: "1.0"
paths:
  /recover-password:
    post:
      consumes:
      - application/json
      description: Recover user password
      parameters:
      - description: Recover Passsword information
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.RecoverPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
      summary: Recover user password
  /reset-password:
    post:
      consumes:
      - application/json
      description: Reset user password with verification token
      parameters:
      - description: Reset User Password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.ResetPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
      summary: Reset user password with verification token
  /sign-in:
    post:
      consumes:
      - application/json
      description: Authenticate user by DNI and Password
      parameters:
      - description: User credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.Auth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "401":
          description: Unauthorized
          schema:
            type: object
      summary: Authenticate user by DNI and Password
  /users:
    post:
      consumes:
      - application/json
      description: Create user
      parameters:
      - description: User Information
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      - description: Authorization Token
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
      summary: Create user
  /users/:dni:
    get:
      consumes:
      - application/json
      description: Get user by DNI
      parameters:
      - description: User DNI
        in: path
        name: query-id
        required: true
        type: string
      - description: Authorization Token
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
      summary: Get user by DNI
  /users/load-by-csv:
    post:
      consumes:
      - multipart/form-data
      description: Load user information by CSV
      parameters:
      - description: CSV file with user information
        in: formData
        name: file
        required: true
        type: file
      - description: Authorization Token
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
      summary: Load user information by CSV
  /users/me:
    get:
      consumes:
      - application/json
      description: Get authenticated user information
      parameters:
      - description: Authorization Token
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
      summary: Get authenticated user information
    patch:
      consumes:
      - application/json
      description: Update authenticated user information
      parameters:
      - description: User information to update
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/domain.UpdateUser'
      - description: Authorization Token
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
      summary: Update authenticated user information
swagger: "2.0"
